version: '3'

services:
  polls_app:
    image: polls_app
    container_name: polls
    build: ./polls
    command: >
      sh -c "python polls/manage.py makemigrations
      && python polls/manage.py migrate
      && python polls/manage.py runserver 0.0.0.0:8001"
    env_file:
      - ./polls/.env
    volumes:
      - ./polls/:/code/polls
    ports:
      - "8001:8001"
  
  questions_app:
    image: questions_app
    container_name: questions
    build: ./questions
    command: >
      sh -c "python questions/manage.py makemigrations
      && python questions/manage.py migrate
      && python questions/manage.py runserver 0.0.0.0:8002"
    env_file:
      - ./questions/.env
    volumes:
      - ./questions/:/code/questions
    ports:
      - "8002:8002"